import type {
  Announcement,
  AuditLog,
  AzkarCategory,
  AzkarItem,
  Donation,
  DonationCampaign,
  DonationReceiptRequest,
  DonationReport,
  DonationSettings,
  Event,
  JumuahTime,
  MosqueSettings,
  PrayerTime,
  RamadanDay,
} from "./types";

export const timezone = "Europe/Berlin";

export const mosqueSettings: MosqueSettings = {
  mosqueName: "IQAMA Masjid Deggendorf",
  mosqueNameAr: "مسجد إقاما ديغندورف",
  mosqueNameEn: "IQAMA Masjid Deggendorf",
  mosqueNameDe: "IQAMA Moschee Deggendorf",
  mosqueNameTr: "IQAMA Deggendorf Camii",
  address: "Musterstrasse 12, 94469 Deggendorf, Germany",
  phone: "+49 991 123456",
  email: "info@deggendorf-prayer.example",
  googleMapsLink: "#",
  whatsappLink: "#",
  telegramLink: "#",
  accountHolder: "Islamische Gemeinde Deggendorf",
  iban: "DE89 3704 0044 0532 0130 00",
  bic: "COBADEFFXXX",
};

export const prayerTimes: PrayerTime[] = [
  ["2026-06-22", "03:18", "05:06", "13:12", "17:31", "21:19", "22:58"],
  ["2026-06-23", "03:18", "05:06", "13:12", "17:31", "21:19", "22:58"],
  ["2026-06-24", "03:19", "05:07", "13:13", "17:32", "21:19", "22:57"],
  ["2026-06-25", "03:20", "05:07", "13:13", "17:32", "21:19", "22:57"],
  ["2026-06-26", "03:21", "05:08", "13:13", "17:33", "21:19", "22:56"],
  ["2026-06-27", "03:22", "05:08", "13:13", "17:33", "21:18", "22:56"],
  ["2026-06-28", "03:23", "05:09", "13:14", "17:33", "21:18", "22:55"],
].map(([date, fajr, sunrise, dhuhr, asr, maghrib, isha], index) => ({
  id: `pt-${index + 1}`,
  date,
  fajr,
  sunrise,
  dhuhr,
  asr,
  maghrib,
  isha,
  fajrIqama: "04:00",
  dhuhrIqama: "13:30",
  asrIqama: "18:00",
  maghribIqama: "21:25",
  ishaIqama: "23:10",
  note: "Times are manually published by mosque administration.",
  noteAr: "تنشر إدارة المسجد هذه المواقيت يدويا.",
  noteEn: "Times are manually published by mosque administration.",
  noteDe: "Die Zeiten werden manuell von der Moscheeverwaltung veröffentlicht.",
  noteTr: "Vakitler cami yönetimi tarafından elle yayınlanır.",
  published: true,
  updatedAt: "2026-06-20T18:30:00+02:00",
}));

export const jumuahTimes: JumuahTime[] = [
  {
    id: "jum-1",
    date: "2026-06-26",
    khutbahTime: "13:15",
    prayerTime: "13:45",
    locationName: "IQAMA Masjid, Deggendorf",
    locationAddress: "Musterstrasse 12, 94469 Deggendorf",
    khateebName: "Shaykh Abdul Rahman",
    language: "Arabic / German / English",
    languageAr: "العربية / الألمانية / الإنجليزية",
    languageEn: "Arabic / German / English",
    languageDe: "Arabisch / Deutsch / Englisch",
    languageTr: "Arapça / Almanca / İngilizce",
    notes: "Please arrive early and keep entrances clear for families.",
    notesAr: "يرجى الحضور مبكرا وإبقاء المداخل خالية للعائلات.",
    notesEn: "Please arrive early and keep entrances clear for families.",
    notesDe: "Bitte komm früh und halte die Eingänge für Familien frei.",
    notesTr: "Lütfen erken gelin ve girişleri aileler için açık tutun.",
    published: true,
  },
];

export const announcements: Announcement[] = [
  {
    id: "ann-1",
    title: "Friday location update",
    titleAr: "تحديث مكان صلاة الجمعة",
    titleEn: "Friday location update",
    titleDe: "Aktualisierung des Freitagsortes",
    titleTr: "Cuma yeri güncellemesi",
    message: "Jumu'ah will be held at IQAMA Masjid this week. Please arrive before the khutbah begins.",
    messageAr: "ستقام صلاة الجمعة هذا الأسبوع في مسجد إقاما. يرجى الحضور قبل بدء الخطبة.",
    messageEn: "Jumu'ah will be held at IQAMA Masjid this week. Please arrive before the khutbah begins.",
    messageDe: "Das Freitagsgebet findet diese Woche in der IQAMA Moschee statt. Bitte komme vor Beginn der Chutba.",
    messageTr: "Cuma namazı bu hafta IQAMA Camii'nde kılınacak. Lütfen hutbe başlamadan önce gelin.",
    type: "Location update",
    isUrgent: true,
    published: true,
    createdAt: "2026-06-24T09:00:00+02:00",
  },
  {
    id: "ann-2",
    title: "Quran class registration",
    titleAr: "التسجيل في درس القرآن",
    titleEn: "Quran class registration",
    titleDe: "Anmeldung zum Korankurs",
    titleTr: "Kur'an dersi kaydı",
    message: "Registration is open for the weekly Quran class for adults and youth.",
    messageAr: "التسجيل مفتوح لدرس القرآن الأسبوعي للبالغين والشباب.",
    messageEn: "Registration is open for the weekly Quran class for adults and youth.",
    messageDe: "Die Anmeldung für den wöchentlichen Korankurs für Erwachsene und Jugendliche ist geöffnet.",
    messageTr: "Yetişkinler ve gençler için haftalık Kur'an dersi kaydı açıldı.",
    type: "Community",
    isUrgent: false,
    published: true,
    createdAt: "2026-06-23T18:30:00+02:00",
  },
  {
    id: "ann-3",
    title: "Support monthly rent",
    titleAr: "دعم الإيجار الشهري",
    titleEn: "Support monthly rent",
    titleDe: "Monatliche Miete unterstützen",
    titleTr: "Aylık kiraya destek",
    message: "The monthly rent campaign is active. Bank transfer details are available on the donations page.",
    messageAr: "حملة الإيجار الشهري نشطة. تفاصيل التحويل البنكي متوفرة في صفحة التبرعات.",
    messageEn: "The monthly rent campaign is active. Bank transfer details are available on the donations page.",
    messageDe: "Die Kampagne für die monatliche Miete ist aktiv. Bankdaten findest du auf der Spendenseite.",
    messageTr: "Aylık kira kampanyası aktif. Banka havalesi bilgileri bağışlar sayfasında bulunur.",
    type: "Donation",
    isUrgent: false,
    published: true,
    createdAt: "2026-06-22T12:00:00+02:00",
  },
];

export const donationSettings: DonationSettings = {
  accountHolder: mosqueSettings.accountHolder,
  iban: mosqueSettings.iban,
  bic: mosqueSettings.bic,
  paypalLink: "",
  defaultPurpose: "Masjid donation",
  defaultPurposeAr: "تبرع للمسجد",
  defaultPurposeEn: "Masjid donation",
  defaultPurposeDe: "Moscheespende",
  defaultPurposeTr: "Cami bağışı",
  receiptNote: "Receipt requests are reviewed manually by the mosque administration.",
  receiptNoteAr: "تراجع إدارة المسجد طلبات الإيصالات يدويا.",
  receiptNoteEn: "Receipt requests are reviewed manually by the mosque administration.",
  receiptNoteDe: "Bescheinigungsanfragen werden manuell von der Moscheeverwaltung geprüft.",
  receiptNoteTr: "Makbuz talepleri cami yönetimi tarafından elle incelenir.",
};

export const donationCampaigns: DonationCampaign[] = [
  {
    id: "camp-1",
    title: "Monthly Rent Support",
    titleAr: "دعم الإيجار الشهري",
    titleEn: "Monthly Rent Support",
    titleDe: "Unterstützung der Monatsmiete",
    titleTr: "Aylık Kira Desteği",
    description: "Help cover rent, utilities, and core mosque operations.",
    descriptionAr: "ساهم في تغطية الإيجار والمرافق وتشغيل المسجد الأساسي.",
    descriptionEn: "Help cover rent, utilities, and core mosque operations.",
    descriptionDe: "Hilf mit, Miete, Nebenkosten und den laufenden Moscheebetrieb zu decken.",
    descriptionTr: "Kira, faturalar ve caminin temel giderlerini karşılamaya destek olun.",
    targetAmount: 4000,
    collectedAmount: 2450,
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    isActive: true,
    isFeatured: true,
  },
  {
    id: "camp-2",
    title: "Ramadan Iftar",
    titleAr: "إفطار رمضان",
    titleEn: "Ramadan Iftar",
    titleDe: "Ramadan-Iftar",
    titleTr: "Ramazan İftarı",
    description: "Support community iftar meals and Ramadan gatherings.",
    descriptionAr: "ادعم وجبات الإفطار الجماعية ولقاءات رمضان.",
    descriptionEn: "Support community iftar meals and Ramadan gatherings.",
    descriptionDe: "Unterstütze gemeinschaftliche Iftar-Mahlzeiten und Ramadan-Treffen.",
    descriptionTr: "Toplu iftar yemeklerini ve Ramazan buluşmalarını destekleyin.",
    targetAmount: 5000,
    collectedAmount: 3120,
    startDate: "2026-02-01",
    endDate: "2026-03-20",
    isActive: true,
    isFeatured: false,
  },
];

export const donations: Donation[] = [
  { id: "don-1", amount: 50, purpose: "Monthly Rent Support", donorName: "Community member", receivedAt: "2026-06-22", method: "Bank transfer" },
  { id: "don-2", amount: 20, purpose: "Masjid donation", receivedAt: "2026-06-23", method: "Cash" },
];

export const receiptRequests: DonationReceiptRequest[] = [
  { id: "rec-1", donorName: "Fatima K.", amount: 150, email: "fatima@example.com", status: "Pending", createdAt: "2026-06-23" },
  { id: "rec-2", donorName: "Omar A.", amount: 80, email: "omar@example.com", status: "Reviewed", createdAt: "2026-06-21" },
];

export const donationReport: DonationReport = {
  month: "June 2026",
  monthlyNeed: 5200,
  donationsReceived: 3570,
  remaining: 1630,
};

export const azkarCategories: AzkarCategory[] = ["Morning", "Evening", "After Prayer", "Sleep", "Travel", "Friday"];

export const azkarItems: AzkarItem[] = [
  {
    id: "az-1",
    category: "Morning",
    arabicText: "اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور",
    transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namut wa ilaykan-nushur.",
    translationAr: "اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور.",
    translationEn: "O Allah, by You we enter the morning and evening, by You we live and die, and to You is the resurrection.",
    translationDe: "O Allah, durch Dich erreichen wir den Morgen und den Abend, durch Dich leben und sterben wir.",
    translationTr: "Allah'ım, Seninle sabaha ve akşama ereriz, Seninle yaşar ve ölürüz, dönüş Sanadır.",
    repeatCount: 1,
    source: "Tirmidhi",
    sortOrder: 1,
    isPublished: true,
  },
  {
    id: "az-2",
    category: "After Prayer",
    arabicText: "سُبْحَانَ اللهِ",
    transliteration: "Subhan Allah",
    translationAr: "سبحان الله.",
    translationEn: "Glory be to Allah.",
    translationDe: "Gepriesen sei Allah.",
    translationTr: "Allah'ı tesbih ederim.",
    repeatCount: 33,
    source: "Sahih Muslim",
    sortOrder: 2,
    isPublished: true,
  },
  {
    id: "az-3",
    category: "Evening",
    arabicText: "لا إله إلا الله وحده لا شريك له",
    transliteration: "La ilaha illa Allah wahdahu la sharika lah.",
    translationAr: "لا إله إلا الله وحده لا شريك له.",
    translationEn: "There is no god but Allah alone, without partner.",
    translationDe: "Es gibt keinen Gott ausser Allah allein, ohne Partner.",
    translationTr: "Allah'tan başka ilah yoktur; O tektir, ortağı yoktur.",
    repeatCount: 10,
    source: "Bukhari and Muslim",
    sortOrder: 3,
    isPublished: true,
  },
];

export const events: Event[] = [
  {
    id: "ev-1",
    title: "Quran class",
    titleAr: "درس القرآن",
    titleEn: "Quran class",
    titleDe: "Korankurs",
    titleTr: "Kur'an dersi",
    date: "2026-06-27",
    startTime: "18:30",
    endTime: "20:00",
    location: "IQAMA Masjid",
    locationAr: "مسجد إقاما",
    locationEn: "IQAMA Masjid",
    locationDe: "IQAMA Moschee",
    locationTr: "IQAMA Camii",
    type: "Class",
    description: "Weekly recitation and tajweed practice for adults.",
    descriptionAr: "تلاوة وتجويد أسبوعي للبالغين.",
    descriptionEn: "Weekly recitation and tajweed practice for adults.",
    descriptionDe: "Wöchentliche Rezitation und Tajweed-Übung für Erwachsene.",
    descriptionTr: "Yetişkinler için haftalık tilavet ve tecvid çalışması.",
  },
  {
    id: "ev-2",
    title: "Community gathering",
    titleAr: "لقاء المجتمع",
    titleEn: "Community gathering",
    titleDe: "Gemeinschaftstreffen",
    titleTr: "Topluluk buluşması",
    date: "2026-06-28",
    startTime: "19:00",
    endTime: "21:00",
    location: "Community hall",
    locationAr: "قاعة المجتمع",
    locationEn: "Community hall",
    locationDe: "Gemeindesaal",
    locationTr: "Topluluk salonu",
    type: "Community",
    description: "Tea, introductions, and community planning.",
    descriptionAr: "شاي وتعارف وتخطيط لأنشطة المجتمع.",
    descriptionEn: "Tea, introductions, and community planning.",
    descriptionDe: "Tee, Kennenlernen und Planung der Gemeinschaft.",
    descriptionTr: "Çay, tanışma ve topluluk planlaması.",
  },
  {
    id: "ev-3",
    title: "Youth event",
    titleAr: "فعالية الشباب",
    titleEn: "Youth event",
    titleDe: "Jugendveranstaltung",
    titleTr: "Gençlik etkinliği",
    date: "2026-07-03",
    startTime: "17:00",
    endTime: "19:00",
    location: "Mosque classroom",
    locationAr: "قاعة التعليم في المسجد",
    locationEn: "Mosque classroom",
    locationDe: "Unterrichtsraum der Moschee",
    locationTr: "Cami dersliği",
    type: "Youth",
    description: "Discussion and activities for young community members.",
    descriptionAr: "نقاش وأنشطة للشباب في المجتمع.",
    descriptionEn: "Discussion and activities for young community members.",
    descriptionDe: "Austausch und Aktivitäten für junge Gemeindemitglieder.",
    descriptionTr: "Genç topluluk üyeleri için sohbet ve etkinlikler.",
  },
  {
    id: "ev-4",
    title: "Sisters event",
    titleAr: "فعالية الأخوات",
    titleEn: "Sisters event",
    titleDe: "Schwesternveranstaltung",
    titleTr: "Hanımlar etkinliği",
    date: "2026-07-05",
    startTime: "15:00",
    endTime: "17:00",
    location: "Women prayer area",
    locationAr: "مصلى النساء",
    locationEn: "Women prayer area",
    locationDe: "Gebetsbereich der Frauen",
    locationTr: "Kadınlar namaz alanı",
    type: "Sisters",
    description: "Monthly sisters circle and planning session.",
    descriptionAr: "حلقة شهرية للأخوات وجلسة تخطيط.",
    descriptionEn: "Monthly sisters circle and planning session.",
    descriptionDe: "Monatlicher Schwesternkreis und Planungstreffen.",
    descriptionTr: "Aylık hanımlar halkası ve planlama buluşması.",
  },
  {
    id: "ev-5",
    title: "Iftar event",
    titleAr: "فعالية إفطار",
    titleEn: "Iftar event",
    titleDe: "Iftar-Veranstaltung",
    titleTr: "İftar etkinliği",
    date: "2026-03-01",
    startTime: "18:00",
    endTime: "20:00",
    location: "IQAMA Masjid",
    locationAr: "مسجد إقاما",
    locationEn: "IQAMA Masjid",
    locationDe: "IQAMA Moschee",
    locationTr: "IQAMA Camii",
    type: "Iftar",
    description: "Community iftar and Ramadan gathering.",
    descriptionAr: "إفطار جماعي ضمن جدول رمضان.",
    descriptionEn: "Community iftar and Ramadan gathering.",
    descriptionDe: "Gemeinschafts-Iftar im Ramadan-Zeitplan.",
    descriptionTr: "Ramazan takvimi için toplu iftar.",
  },
];

export const ramadanDays: RamadanDay[] = [
  {
    id: "ram-1",
    date: "2026-02-18",
    ramadanDay: 1,
    imsak: "05:08",
    fajr: "05:18",
    maghrib: "17:39",
    iftar: "17:39",
    taraweeh: "19:30",
    note: "Ramadan schedule managed by the mosque administration.",
    noteAr: "جدول رمضان تجريبي.",
    noteEn: "Ramadan schedule managed by the mosque administration.",
    noteDe: "Platzhalter für den Ramadan-Kalender.",
    noteTr: "Ramazan takvimi yer tutucusu.",
  },
  { id: "ram-2", date: "2026-02-19", ramadanDay: 2, imsak: "05:06", fajr: "05:16", maghrib: "17:41", iftar: "17:41", taraweeh: "19:30" },
];

export const auditLogs: AuditLog[] = [
  { id: "log-1", actor: "Ahmed", action: "changed Asr time on 2026-07-01 from 17:20 to 17:30", createdAt: "2026-06-24 10:15" },
  { id: "log-2", actor: "Admin", action: "created donation campaign Monthly Rent Support", createdAt: "2026-06-23 18:40" },
  { id: "log-3", actor: "Admin", action: "published Friday location update", createdAt: "2026-06-23 09:12" },
];
